### ISSUE TITLE
can't be used in webpack build environment

### ISSUE THREAD

**Issue by jamuhl** [mzabriskie/react-tabs#11]
we would love to use this in our project. but we use webpack for our build, bundling process. As the component files are saved ending .js there is a configuration overhead (webback transforms just jsx files).

as we got multiple projects having to put special configurations to every project - so right now simplest solution would be to create a fork (renaming the files to abc.jsx or serve already transformed files in that fork.)

https://github.com/JedWatson/react-select/issues/40 is an interesting discussion about the same topic.

do you consider to optimize this for webpack usage?!?

**Comment by ericdfields** [comment]
Yeah, just running into this myself. Considering all the lib/components do have JSX in them, why not rename them from .js to .jsx?

**Comment by ericdfields** [comment]
@jamuhl actually is that the problem? I forked and renamed the components and get this error for each component:

````bash
ERROR in ../~/react-tabs/lib/components/TabPanel.jsx
Module parse failed: /Users/EricFields/Development/vanda/node_modules/react-tabs/lib/components/TabPanel.jsx Line 24: Unexpected token <
You may need an appropriate loader to handle this file type.
| 
| 		return (
| 			<div role="tabpanel"
| 				id={this.props.id}
| 				aria-labeledby={this.props.tabId}
 @ ../~/react-tabs/lib/main.js 5:11-43
````

**Comment by jamuhl** [comment]
@ericdfields sorry...can't remember...we had a bigger change so we had no need to use this....sorry.

**Comment by anyong** [comment]
Can't use it in browserify either. Here's the errors:

tabpanel.js: Unexpected token (19:3)
tab.js: Unexpected token (42:3)
tablist.js: Unexpected token (7:3)
tabs.js: Unexpected token (201:3)

Same issue renaming them to .jsx.

Seems like it might be pretty straightforward to pre-transpile and load react-tabs into a single .js file for distribution?

**Comment by mzabriskie** [comment]
I have completely removed JSX (https://github.com/mzabriskie/react-tabs/commit/8d47d98b92a83be3674d53db6dc1e29ef6310d64). This should no longer be an issue once it's released.
