### ISSUE TITLE
React 0.13 support?

### ISSUE THREAD

**Issue by iamdustan** [mzabriskie/react-tabs#19]
Hey @mzabriskie,

Would you accept a PR that updated this to work with React 0.13? I see there are a few open PRs and don’t want to put in the effort if it will be left neglected. What are your requirements and constraints to accept 0.13 support?

**Comment by neilgupta** [comment]
Even if he doesn't, there are others who would be interested in said PR :)

**Comment by iamdustan** [comment]
ha. Agreed, but I’m not going to maintain a fork.

**Comment by iamdustan** [comment]
I’m still getting errors due to the jsx pragma.

```
ERROR in ./~/react-tabs/lib/tabpanel.js
Module build failed: SyntaxError: /Users/iamdustan/projects/skookum/node_modules/react-tabs/lib/tabpanel.js: Line 1: The @jsx React.DOM pragma has been deprecated as of React 0.12
```
