### ISSUE TITLE
"Moving stuff around" breaks clean update for Tweed

### ISSUE THREAD

**Issue by canadaduane** [mzabriskie/react-tabs#20]
This is just a placeholder for a conversation to be had about how to use the latest react-tabs in Tweed. Currently, SHA a3f400a and forward seems to be giving us grief. Possibly because of React 0.13 incompat?

**Comment by mzabriskie** [comment]
Try installing the latest commit and let me know if it's working.

**Comment by mzabriskie** [comment]
Fixed with 83f80267cdc59eb6202eaec7f961cd283ebcc526.
