### ISSUE TITLE
Bundling of React in /dist files

### ISSUE THREAD

**Issue by jacktasia** [mzabriskie/react-tabs#26]
So I believe this is related to #23 and #15. 

I can't figure out why all of React is bundled inside of `dist/react-tabs.js` and `dist/react-tabs.min.js`. As far as I can tell this makes it impossible to include `react-tabs` on a project that already has `React` as a dependency. Ideally we wouldn't be dependent on a single plugin to provide the version of React that everything in a project would use. This seems to be a particular problem when using `bower`. As far as this warning:

> Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's render method). Try rendering this component inside of a new top-level component which will hold the ref.

Am I missing something? Or would it be possible to include a `/dist` version of `react-tabs` that doesn't include React itself?

**Comment by mzabriskie** [comment]
@jacktasia this has been fixed with 0.4.1

**Comment by jacktasia** [comment]
@mzabriskie Nice! Thanks for the heads up.
