### ISSUE TITLE
Add tab dinamicaly

### ISSUE THREAD

**Issue by isergey** [mzabriskie/react-tabs#35]
Hello! Thank you for the library! I have a question about dynamic addition of tabs. In pseudo code it's looks like this:

```
handleAddProfileClick() {
    this.refs.tabs.add(
     <UserProfileTab userId="123" />
    );
},
handleAddSettingsClick() {
    this.refs.tabs.add(
     <Settings  />
    );
}
``` 
It is also important that other tabs are not redrawn (kept its state).
How about tab closing?
Thanks a lot!

**Comment by mzabriskie** [comment]
I have an example of dynamically adding/removing tabs here https://github.com/mzabriskie/react-tabs/tree/master/examples/dyno

**Comment by isergey** [comment]
Thank you!

**Comment by themre** [comment]
Thanks for this! However I would like to add tabs dynamically by passing certain Component inside like:
```
addTab("tab text", <MyComponent />);
```
Any way to achieve this?
